"""Browser test: Add New Title form with a custom Book ID.  Starts its own server on a DB copy (needs free port 3000)."""
import json, os, shutil, subprocess, sys, tempfile, time, urllib.request
from playwright.sync_api import sync_playwright

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "http://127.0.0.1:3000"
res = []
def ok(c, m, x=""):
    res.append(bool(c)); print(("  ✔ " if c else "  ✘ ") + m + ((" -> " + str(x)[:250]) if (not c and x != "") else ""))
def get(path): return json.loads(urllib.request.urlopen(BASE + path, timeout=10).read())

try:
    urllib.request.urlopen(BASE + "/api/ai/status", timeout=1); print("Port 3000 is busy - stop the running server first."); sys.exit(2)
except Exception:
    pass

tmp = tempfile.mkdtemp(); db = os.path.join(tmp, "t.db"); subprocess.run(["node", "server/test-support/build-test-db.js", db], cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
srv = subprocess.Popen(["node", "server/server-complete.js"], cwd=ROOT, env=dict(os.environ, PORT="3000", HOST="127.0.0.1", DATABASE_PATH=db, ANTHROPIC_API_KEY=""), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
for _ in range(60):
    time.sleep(0.5)
    try: urllib.request.urlopen(BASE + "/api/ai/status", timeout=1); break
    except Exception: pass

TAG = str(int(time.time()))[-6:]
def fill_book(page, title, bid=None):
    page.evaluate("app.openModal('add-book')"); page.wait_for_selector("#nb-id")
    if bid is not None: page.fill("#nb-id", str(bid))
    page.fill("#nb-title", title); page.fill("#nb-author", "UI Tester")
def toast(page): return page.inner_text("#toast-root")

try:
    with sync_playwright() as pw:
        b = pw.chromium.launch(); page = b.new_page(viewport={"width": 1300, "height": 900})
        errors = []
        page.on("pageerror", lambda e: errors.append(str(e)) if not any(i in str(e) for i in ("Chart", "emailjs", "LuminaLibrary is not defined")) else None)
        page.goto(BASE); page.wait_for_selector("#auth-username"); page.click("form button[type=submit]")
        page.wait_for_selector(".app-container", state="visible"); page.click('button[data-view="catalog"]'); page.wait_for_selector("text=+ Add New Title")

        print("\n1. The Book ID box is editable (no longer locked 'Auto-Generated')")
        page.click("text=+ Add New Title"); page.wait_for_selector("#nb-id")
        el = page.locator("#nb-id")
        ok(el.is_editable() and el.get_attribute("readonly") is None, "Book ID input is editable")
        ok("Auto-Generated" not in page.inner_text("#modal-content"), "old locked 'Auto-Generated by Database' text is gone")
        nxt = max(x["bookID"] for x in get("/api/bootstrap")["books"]) + 1
        ok(f"#{nxt}" in el.get_attribute("placeholder") and f"#{nxt}" in page.inner_text("#nb-id-hint"), f"placeholder/hint show the next free ID (#{nxt})", el.get_attribute("placeholder"))

        print("\n2. Live hint while typing")
        used = get("/api/bootstrap")["books"][0]
        page.fill("#nb-id", str(used["bookID"]))
        h = page.inner_text("#nb-id-hint"); ok("already used" in h and used["title"] in h, "typing a taken ID warns immediately and names the book", h)
        page.fill("#nb-id", "987654"); ok("is free" in page.inner_text("#nb-id-hint"), "a free ID shows ✔ free")
        page.fill("#nb-id", ""); ok("auto-assign" in page.inner_text("#nb-id-hint"), "clearing the box shows the auto-assign hint")
        page.evaluate("app.closeModal()")

        print("\n3. Save with my own ID")
        fill_book(page, f"Custom ID Book {TAG}", 424242)
        page.click("#modal-content button[type=submit]"); page.wait_for_function("document.getElementById('toast-root').innerText.includes('424242')")
        ok("#424242" in toast(page), "toast confirms 'Book ID #424242'", toast(page))
        saved = [x for x in get("/api/bootstrap")["books"] if x["bookID"] == 424242]
        ok(len(saved) == 1 and saved[0]["title"] == f"Custom ID Book {TAG}", "the database really holds the book under #424242")
        page.wait_for_selector(f"text=Custom ID Book {TAG}"); ok(page.locator(f"text=Custom ID Book {TAG}").count() >= 1, "the new book appears in the catalog list")
        page.reload(); page.wait_for_selector(".app-container", state="visible"); page.click('button[data-view="catalog"]')
        ok(page.locator(f"text=Custom ID Book {TAG}").count() >= 1, "the book is still there after a page reload")

        print("\n4. Duplicate ID is refused with a clear message")
        fill_book(page, f"Dup Try {TAG}", 424242)
        page.click("#modal-content button[type=submit]"); page.wait_for_function("document.getElementById('toast-root').innerText.includes('already used')")
        ok(f"Custom ID Book {TAG}" in toast(page), "toast: 'Book ID #424242 is already used by …'", toast(page))
        ok(page.locator("#nb-id").count() == 1, "form stays open so the ID can be corrected")
        ok(len([x for x in get("/api/bootstrap")["books"] if x["title"] == f"Dup Try {TAG}"]) == 0, "nothing was created")
        page.fill("#nb-id", "424243"); page.click("#modal-content button[type=submit]")
        page.wait_for_function("document.getElementById('toast-root').innerText.includes('424243')")
        page.wait_for_selector("#app-modal", state="hidden")
        ok(any(x["bookID"] == 424243 for x in get("/api/bootstrap")["books"]), "after fixing the ID the same form saves it")

        print("\n5. Leaving it empty still auto-assigns")
        before = max(x["bookID"] for x in get("/api/bootstrap")["books"])
        fill_book(page, f"Auto ID Book {TAG}")
        page.click("#modal-content button[type=submit]"); page.wait_for_function("(t)=>document.getElementById('toast-root').innerText.includes(t)", arg=f"Auto ID Book {TAG}")
        page.wait_for_selector("#app-modal", state="hidden")
        auto = [x for x in get("/api/bootstrap")["books"] if x["title"] == f"Auto ID Book {TAG}"]
        ok(len(auto) == 1 and auto[0]["bookID"] == before + 1, f"empty ID -> auto #{before + 1}", auto)

        print("\n6. Bad input")
        fill_book(page, f"Zero {TAG}", 0)
        n_books = len(get("/api/bootstrap")["books"])
        page.click("#modal-content button[type=submit]"); page.wait_for_timeout(800)
        ok(page.eval_on_selector("#nb-id", "e => e.validity.rangeUnderflow") is True, "0 is blocked by the browser's own validation (minimum 1)")
        ok(page.locator("#nb-id").count() == 1 and len(get("/api/bootstrap")["books"]) == n_books, "form stays open and nothing is created")
        page.fill("#nb-id", "-7"); page.click("#modal-content button[type=submit]"); page.wait_for_timeout(500)
        ok(page.eval_on_selector("#nb-id", "e => e.validity.rangeUnderflow") is True and len(get("/api/bootstrap")["books"]) == n_books, "-7 is blocked too")
        ok(not errors, "no JavaScript errors", errors[:3])
        page.screenshot(path="/tmp/bookid_form.png")
        b.close()
finally:
    srv.terminate(); time.sleep(0.5); shutil.rmtree(tmp, ignore_errors=True)
print(f"\n==== Custom Book ID browser checks: {sum(res)} passed, {len(res)-sum(res)} failed ====")
sys.exit(0 if all(res) else 1)
